[theme]
primaryColor = "#0B5ED7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6FC"
textColor = "#061A40"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

